version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=datamaster
    volumes:
      - ./postgres_data:/bitnami/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres_data:
